Added a Way to select the number of columns for a image in FO
PrestaShop/themeconfigurator pull request #20
Opened 2018-03-05 19:56 UTC by jdperea

![image](https://user-images.githubusercontent.com/4968958/36996522-0b7f8060-2085-11e8-98df-b80b37db04e2.png)

Please give me a feed back to make my code better.
I have to set the values (width and height) of images to 0 to use 100% of div

2020-04-28 08:55 UTC, Progi1984 commented on views/templates/hook/hook.tpl
> +				<li class="htmlcontent-item-{$smarty.foreach.items.iteration|escape:'htmlall':'UTF-8'} col-xs-4  {$hItem.columns} {if $hItem.columns > 1}item-{$hItem.columns}-col{/if}">
```suggestion
				<li class="htmlcontent-item-{$smarty.foreach.items.iteration|escape:'htmlall':'UTF-8'} col-xs-4{$hItem.columns} {if $hItem.columns > 1}item-{$hItem.columns}-col{/if}">
```

2020-04-28 08:55 UTC, Progi1984 commented on themeconfigurator.php
> +					`id_shop`, `id_lang`, `item_order`, `title`, `title_use`, `hook`, `url`, `target`, `image`, `image_w`, `image_h`, `html`,`columns`, `active`
```suggestion
					`id_shop`, `id_lang`, `item_order`, `title`, `title_use`, `hook`, `url`, `target`, `image`, `image_w`, `image_h`, `html`, `columns`, `active`
```

2020-04-28 08:56 UTC, Progi1984 commented on themeconfigurator.php
> +        $columns = (int)Tools::getValue('item_columns');
```suggestion
		$content = Tools::getValue('item_html');
        	$columns = (int)Tools::getValue('item_columns');
```

2020-04-28 08:58 UTC, Progi1984 requested changes
Thank you for your contribution @jdperea.

Some improvements : 
- if columns are defined, please hide width & height input boxes 
- add a sql migration script for update

2020-05-28 08:07 UTC, matks commented
Hi and thanks for your contribution.

This repository is now deprecated. Sorry for the late answer 😞 

Kind regards

2020-05-28 08:07 UTC, closed without merging